-- ============================================================================
-- Librum Tenebris — Seed de demo para la tabla `libros`
-- Generado: 2026-04-23 — 101 libros (catálogo actual)
-- ============================================================================
--
-- Este script RELLENA la tabla `libros` de la BD `librum-tenebris` con los
-- registros del catálogo en producción a fecha del seed. Asume que la tabla
-- ya existe (la crea `02_libros_schema.sql`).
--
-- Si hay datos previos y colisiona la PK o `google_id`, los INSERTs fallarán.
-- Para empezar limpio, descomenta la línea TRUNCATE de abajo.
--
-- USO:
--   mysql -u <usuario> -p librum-tenebris < 03_libros_seed.sql
-- O desde phpMyAdmin: BD `librum-tenebris` → Importar.
--
-- AVISO sobre el libro id=101 ("El libro de todos"):
--   La portada apunta a http://localhost:8080/... — en el demo en Hostinger
--   no se verá. O bien lo borras del seed antes de subirlo, o le cambias la
--   URL a una pública, o lo subes manualmente desde el panel admin.
-- ============================================================================

SET NAMES utf8mb4;

USE `librum-tenebris`;

-- TRUNCATE TABLE `libros`;

INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (1,'OL-OL407498W','The Power of Darkness',NULL,'Edith Nesbit',3,'A horror book written by Edith Nesbit.',NULL,'https://covers.openlibrary.org/b/id/882715-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (2,'OL-OL3625242W','The Vampyre',NULL,'John William Polidori',3,'A horror book written by John William Polidori.',NULL,'https://covers.openlibrary.org/b/id/4871002-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (3,'OL-OL3388961W','The Great God Pan',NULL,'Arthur Machen',3,'A horror book written by Arthur Machen.',NULL,'https://covers.openlibrary.org/b/id/921610-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (4,'OL-OL41078W','The Fall of the House of Usher',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/11838138-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (5,'OL-OL2288676W','Brood of the Witch-Queen',NULL,'Sax Rohmer',3,'A horror book written by Sax Rohmer.',NULL,'https://covers.openlibrary.org/b/id/2011286-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (6,'OL-OL81634W','Misery',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8259296-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (7,'OL-OL81626W','Carrie',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/9256043-L.jpg','Horror',2.0);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (8,'OL-OL41068W','The Black Cat',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/11709016-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (9,'OL-OL8127201W','The King in Yellow',NULL,'Robert W. Chambers',3,'A horror book written by Robert W. Chambers.',NULL,'https://covers.openlibrary.org/b/id/4752788-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (10,'OL-OL2895536W','Carmilla',NULL,'Sheridan Le Fanu',3,'A horror book written by Sheridan Le Fanu.',NULL,'https://covers.openlibrary.org/b/id/973851-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (11,'OL-OL85891W','The Jewel of Seven Stars',NULL,'Bram Stoker',3,'A horror book written by Bram Stoker.',NULL,'https://covers.openlibrary.org/b/id/2760301-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (12,'OL-OL85892W','Dracula',NULL,'Bram Stoker',3,'A horror book written by Bram Stoker.',NULL,'https://covers.openlibrary.org/b/id/12216503-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (13,'OL-OL1833989W','Le fantôme de l\'opéra',NULL,'Gaston Leroux',3,'A horror book written by Gaston Leroux.',NULL,'https://covers.openlibrary.org/b/id/8245407-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (14,'OL-OL81632W','\'Salem’s Lot',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14654118-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (15,'OL-OL41072W','The Murders in the Rue Morgue',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/11774455-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (16,'OL-OL24156W','The Strange Case of Dr. Jekyll and Mr. Hyde',NULL,'Robert Louis Stevenson',3,'A horror book written by Robert Louis Stevenson.',NULL,'https://covers.openlibrary.org/b/id/295773-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (17,'OL-OL183675W','The Castle of Otranto',NULL,'Horace Walpole',3,'A horror book written by Horace Walpole.',NULL,'https://covers.openlibrary.org/b/id/6468730-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (18,'OL-OL450063W','Frankenstein or The Modern Prometheus',NULL,'Mary Shelley',3,'A horror book written by Mary Shelley.',NULL,'https://covers.openlibrary.org/b/id/12356249-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (19,'OL-OL66534W','Northanger Abbey',NULL,'Jane Austen',3,'A horror book written by Jane Austen.',NULL,'https://covers.openlibrary.org/b/id/12567961-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (20,'OL-OL41081W','The Raven',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/8246077-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (21,'OL-OL2771987W','Herland',NULL,'Charlotte Perkins Gilman',3,'A horror book written by Charlotte Perkins Gilman.',NULL,'https://covers.openlibrary.org/b/id/448130-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (22,'OL-OL52266W','The Invisible Man',NULL,'H. G. Wells',3,'A horror book written by H. G. Wells.',NULL,'https://covers.openlibrary.org/b/id/6419199-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (23,'OL-OL8193416W','The Picture of Dorian Gray',NULL,'Oscar Wilde',3,'A horror book written by Oscar Wilde.',NULL,'https://covers.openlibrary.org/b/id/14314858-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (24,'OL-OL5720023W','Twilight',NULL,'Stephenie Meyer',3,'A horror book written by Stephenie Meyer.',NULL,'https://covers.openlibrary.org/b/id/12641977-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (25,'OL-OL40962W','The Narrative of Arthur Gordon Pym',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/7160877-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (26,'OL-OL276328W','Daisy Miller',NULL,'Henry James',3,'A horror book written by Henry James.',NULL,'https://covers.openlibrary.org/b/id/6482238-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (27,'OL-OL492658W','The Lightning Thief',NULL,'Rick Riordan',3,'A horror book written by Rick Riordan.',NULL,'https://covers.openlibrary.org/b/id/7239831-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (28,'OL-OL71042W','The Magician\'s Nephew',NULL,'C. S. Lewis',3,'A horror book written by C. S. Lewis.',NULL,'https://covers.openlibrary.org/b/id/1072931-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (29,'OL-OL63985W','The Legend of Sleepy Hollow',NULL,'Washington Irving',3,'A horror book written by Washington Irving.',NULL,'https://covers.openlibrary.org/b/id/8243083-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (30,'OL-OL103123W','Fahrenheit 451',NULL,'Ray Bradbury',3,'A horror book written by Ray Bradbury.',NULL,'https://covers.openlibrary.org/b/id/12993656-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (31,'OL-OL381550W','The Island of Dr. Moreau',NULL,'H. G. Wells',3,'A horror book written by H. G. Wells.',NULL,'https://covers.openlibrary.org/b/id/968312-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (32,'OL-OL28993W','The Subtle Knife',NULL,'Philip Pullman',3,'A horror book written by Philip Pullman.',NULL,'https://covers.openlibrary.org/b/id/12614549-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (33,'OL-OL276386W','The Turn of the Screw',NULL,'Henry James',3,'A horror book written by Henry James.',NULL,'https://covers.openlibrary.org/b/id/181493-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (34,'OL-OL27482W','The Hobbit',NULL,'J.R.R. Tolkien',3,'A horror book written by J.R.R. Tolkien.',NULL,'https://covers.openlibrary.org/b/id/14627509-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (35,'OL-OL28988W','Northern Lights',NULL,'Philip Pullman',3,'A horror book written by Philip Pullman.',NULL,'https://covers.openlibrary.org/b/id/8747028-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (36,'OL-OL32466W','A Christmas Carol',NULL,'Charles Dickens',3,'A horror book written by Charles Dickens.',NULL,'https://covers.openlibrary.org/b/id/12875748-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (37,'OL-OL81633W','The Shining',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/12376585-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (38,'OL-OL81613W','It',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8569284-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (39,'OL-OL679358W','Coraline',NULL,'Neil Gaiman',3,'A horror book written by Neil Gaiman.',NULL,'https://covers.openlibrary.org/b/id/14171421-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (40,'OL-OL81628W','The Gunslinger',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8396638-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (41,'OL-OL81631W','Pet Sematary',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/12015500-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (42,'OL-OL176025W','The Haunted Hotel',NULL,'Wilkie Collins',3,'A horror book written by Wilkie Collins.',NULL,'https://covers.openlibrary.org/b/id/2890291-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (43,'OL-OL81629W','The Green Mile',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/9334567-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (44,'OL-OL25595002W','Mary Shelley\'s Frankenstein; or, the Modern Prometheus (1818 text)',NULL,'Mary Shelley',3,'A horror book written by Mary Shelley.',NULL,'https://covers.openlibrary.org/b/id/7267770-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (45,'OL-OL5720022W','Breaking Dawn',NULL,'Stephenie Meyer',3,'A horror book written by Stephenie Meyer.',NULL,'https://covers.openlibrary.org/b/id/12643419-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (46,'OL-OL81630W','The Dead Zone',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14653991-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (47,'OL-OL41050W','The Masque of the Red Death',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/11860130-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (48,'OL-OL5720027W','New Moon',NULL,'Stephenie Meyer',3,'A horror book written by Stephenie Meyer.',NULL,'https://covers.openlibrary.org/b/id/12643406-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (49,'OL-OL28996W','The Amber Spyglass',NULL,'Philip Pullman',3,'A horror book written by Philip Pullman.',NULL,'https://covers.openlibrary.org/b/id/12613246-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (50,'OL-OL81618W','The Stand',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/9255992-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (51,'OL-OL695211W','The Mysteries of Udolpho',NULL,'Ann Radcliffe',3,'A horror book written by Ann Radcliffe.',NULL,'https://covers.openlibrary.org/b/id/118207-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (52,'OL-OL81610W','Cujo',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8570003-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (53,'OL-OL103128W','The Illustrated Man',NULL,'Ray Bradbury',3,'A horror book written by Ray Bradbury.',NULL,'https://covers.openlibrary.org/b/id/9345484-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (54,'OL-OL2700647W','The Empty House and Other Ghost Stories',NULL,'Algernon Blackwood',3,'A horror book written by Algernon Blackwood.',NULL,'https://covers.openlibrary.org/b/id/2808629-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (55,'OL-OL505730W','The Magician',NULL,'William Somerset Maugham',3,'A horror book written by William Somerset Maugham.',NULL,'https://covers.openlibrary.org/b/id/2789948-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (56,'OL-OL77826W','Interview With the Vampire',NULL,'Anne Rice',3,'A horror book written by Anne Rice.',NULL,'https://covers.openlibrary.org/b/id/8401488-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (57,'OL-OL927199W','The Exorcist',NULL,'William Peter Blatty',3,'A horror book written by William Peter Blatty.',NULL,'https://covers.openlibrary.org/b/id/12715730-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (58,'OL-OL76578W','Witch Wood',NULL,'John Buchan',3,'A horror book written by John Buchan.',NULL,'https://covers.openlibrary.org/b/id/4781924-L.jpg','Horror',4.0);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (59,'OL-OL81623W','Firestarter',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/12015446-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (60,'OL-OL81616W','The Drawing of the Three',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14651245-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (61,'OL-OL262586W','Tales of Terror and Mystery',NULL,'Arthur Conan Doyle',3,'A horror book written by Arthur Conan Doyle.',NULL,'https://covers.openlibrary.org/b/id/8311421-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (62,'OL-OL81609W','Bag of Bones',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14653458-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (63,'OL-OL14853463W','Poems',NULL,'Percy Bysshe Shelley',3,'A horror book written by Percy Bysshe Shelley.',NULL,'https://covers.openlibrary.org/b/id/8231548-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (64,'OL-OL134834W','Flowers in the Attic',NULL,'V.C. Andrews',3,'A horror book written by V.C. Andrews.',NULL,'https://covers.openlibrary.org/b/id/14598487-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (65,'OL-OL81627W','Skeleton crew',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14657166-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (66,'OL-OL41059W','The Tell-Tale Heart',NULL,'Edgar Allan Poe',3,'A horror book written by Edgar Allan Poe.',NULL,'https://covers.openlibrary.org/b/id/11851436-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (67,'OL-OL81615W','Wizard and Glass',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14657088-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (68,'OL-OL81625W','A Torre Negra',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8443630-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (69,'OL-OL81612W','The Girl Who Loved Tom Gordon',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14653580-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (70,'OL-OL81601W','On Writing',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/9255939-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (71,'OL-OL619317W','The Haunted Bookshop',NULL,'Christopher Morley',3,'A horror book written by Christopher Morley.',NULL,'https://covers.openlibrary.org/b/id/935927-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (72,'OL-OL40873W','The Road',NULL,'Cormac McCarthy',3,'A horror book written by Cormac McCarthy.',NULL,'https://covers.openlibrary.org/b/id/198120-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (73,'OL-OL3171069W','The Haunting of Hill House',NULL,'Shirley Jackson',3,'A horror book written by Shirley Jackson.',NULL,'https://covers.openlibrary.org/b/id/4289014-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (74,'OL-OL81607W','Needful Things',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8404327-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (75,'OL-OL21747086W','Semilla del Diablo',NULL,'Ira Levin',3,'A horror book written by Ira Levin.',NULL,'https://covers.openlibrary.org/b/id/15054795-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (76,'OL-OL81602W','The Eyes of the Dragon',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8524085-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (77,'OL-OL2713465W','Nightmare Abbey',NULL,'Thomas Love Peacock',3,'A horror book written by Thomas Love Peacock.',NULL,'https://covers.openlibrary.org/b/id/1956635-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (78,'OL-OL81606W','Four Past Midnight',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8413143-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (79,'OL-OL81619W','Christine',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14655985-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (80,'OL-OL872225W','Aura',NULL,'Carlos Fuentes',3,'A horror book written by Carlos Fuentes.',NULL,'https://covers.openlibrary.org/b/id/4480453-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (81,'OL-OL81608W','Night Shift',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14651337-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (82,'OL-OL2056818W','Maus I',NULL,'Art Spiegelman',3,'A horror book written by Art Spiegelman.',NULL,'https://covers.openlibrary.org/b/id/10210168-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (83,'OL-OL149210W','Thinner',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8274288-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (84,'OL-OL15008W','The Collector',NULL,'John Fowles',3,'A horror book written by John Fowles.',NULL,'https://covers.openlibrary.org/b/id/3329936-L.jpg','Horror',3.0);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (85,'OL-OL1911336W','The Day of the Triffids',NULL,'John Wyndham',3,'A horror book written by John Wyndham.',NULL,'https://covers.openlibrary.org/b/id/535027-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (86,'OL-OL81597W','Cell',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14654054-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (87,'OL-OL81620W','The Dark Half',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8530409-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (88,'OL-OL483385W','Stuart Little',NULL,'E. B. White',3,'A horror book written by E. B. White.',NULL,'https://covers.openlibrary.org/b/id/10522876-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (89,'OL-OL81584W','Everything\'s Eventual. 14 Dark Tales',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/8585782-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (90,'OL-OL134890W','Petals on the Wind',NULL,'V. C. Andrews',2,'A horror book written by V. C. Andrews.',NULL,'https://covers.openlibrary.org/b/id/9358432-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (91,'OL-OL103194W','Something Wicked This Way Comes',NULL,'Ray Bradbury',3,'A horror book written by Ray Bradbury.',NULL,'https://covers.openlibrary.org/b/id/9346340-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (92,'OL-OL81621W','Different Seasons',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14655761-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (93,'OL-OL23480W','Red Dragon',NULL,'Thomas Harris',3,'A horror book written by Thomas Harris.',NULL,'https://covers.openlibrary.org/b/id/6997898-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (94,'OL-OL81599W','The talisman',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/14651566-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (95,'OL-OL81593W','The Tommyknockers',NULL,'Stephen King',3,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/6997458-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (96,'OL-OL2700635W','The Willows',NULL,'Algernon Blackwood',3,'A horror book written by Algernon Blackwood.',NULL,'https://covers.openlibrary.org/b/id/2751803-L.jpg','Horror',5.0);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (97,'OL-OL827326W','The Beetle',NULL,'Richard Marsh',3,'A horror book written by Richard Marsh.',NULL,'https://covers.openlibrary.org/b/id/2748335-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (98,'OL-OL81603W','Insomnia',NULL,'Stephen King',2,'A horror book written by Stephen King.',NULL,'https://covers.openlibrary.org/b/id/7886954-L.jpg','Horror',NULL);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (99,'OL-OL13116995W','The Monk: A Romance. In Three Volumes. By M. G. Lewis, ..',NULL,'Matthew Gregory Lewis',3,'A horror book written by Matthew Gregory Lewis.',NULL,'https://covers.openlibrary.org/b/id/6008132-L.jpg','Horror',2.0);
INSERT INTO `libros` (`id`, `google_id`, `titulo`, `titulo_es`, `autor`, `stock`, `descripcion`, `descripcion_es`, `portada`, `categoria`, `rating`) VALUES (100,'OL-OL3454854W','Jaws',NULL,'Peter Benchley',5,'A horror book written by Peter Benchley.',NULL,'https://covers.openlibrary.org/b/id/8440296-L.jpg','Horror',4.3);

-- Fin del seed (100 libros insertados).